[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.18.2"
  NPM_VERSION = "9.8.1"

# Plugin de Next.js para Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuración de funciones
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirects para API routes
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

# Headers para mejorar SEO y seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para assets estáticos
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 